force-app/main/default/objects/Session_Time__c/Session_Time__c.object-meta.xml
<CustomObject>
    <label>Session Time</label>
    <nameField>
        <label>Session Time Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Session_Time__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Session_Times</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Time__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Session Times</relationshipLabel>
    <relationshipName>Session_Times</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/setDefaultSessionValuesCtrl.cls
public class setDefaultSessionValuesCtrl{
    /*@AuraEnabled
public static Session_Time__c sessionDefaultDetails()
{
Id currentUserId = UserInfo.getUserId();
Product2 prd = [select id from Product2 where Id='01tNS000007vvlXYAQ'];
RecordType recType = [select id ,name from RecordType where id='012NS000002rLQ9YAM'];
Date Todaydate = system.today();
Session_Time__c sessionRecord = [select Id,Agent__c,Date__c,Product__c from Session_Time__c ];
sessionRecord.Agent__c=  currentUserId;
sessionRecord.Date__c = system.today();
sessionRecord.Product__c=prd.id;
sessionRecord.RecordTypeId=recType.id;
return sessionRecord;
}*/
    @AuraEnabled
    public static Product2 getProduct() {
        // Query to get a product ID
        Product2 product = [SELECT Id FROM Product2 where Id='01tNS000007vvlXYAQ' LIMIT 1];
        return product;
        
    }
}